#-------------------------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See https://go.microsoft.com/fwlink/?linkid=2090316 for license information.
#-------------------------------------------------------------------------------------------------------------

    version: '3'
    services:
      devcontainer:
        # Uncomment the next line to use a non-root user for all processes. You can also
        # simply use the "remoteUser" property in devcontainer.json if you just want VS Code
        # and its sub-processes (terminals, tasks, debugging) to execute as the user. On Linux,
        # you may need to update USER_UID and USER_GID in .devcontainer/Dockerfile to match your
        # user if not 1000. See https://aka.ms/vscode-remote/containers/non-root for details.
        # user: node
    
        build: 
          context: .
          dockerfile: Dockerfile
          args:
            VARIANT: 3

        # In order to run iptable commands, you will need to enable NET_ADMIN capabilities when running docker
        # https://unix.stackexchange.com/questions/459206/list-ip-tables-in-docker-container
        # https://docs.docker.com/compose/compose-file/
        cap_add: 
          - ALL
      
        environment: 
          - SAM_CLI_TELEMETRY=0     # do not send telemetry from aws sam cli tool
          - VSC_DIND=nonroot        # options: root (please remove remoteUser setting in devcontainer.json), nonroot, dind (requires -privileged above)
          - AWS_SDK_LOAD_CONFIG=1   # enable SharedConfigEnable for fargate cli (https://docs.aws.amazon.com/sdk-for-go/api/aws/session/#hdr-Sessions_options_from_Shared_Config)
        
        volumes:
          # Update this to wherever you want VS Code to mount the folder of your project
          # Note that $HOME and $USERPROFILE is placed together because only one variable exsts in either WIndows or POSIX environments
          - ..:/workspace:cached
          - $HOME$USERPROFILE/.aws:/root/.aws:cached
          - $HOME$USERPROFILE/.aws:/home/vscode/.aws:cached
          
          # Forwards the local Docker socket to the container.
          - /var/run/docker.sock:/var/run/docker-host.sock